### ISSUE TITLE
Support for newer versions of ActiveRecord

### ISSUE THREAD

**Issue by jhirbour** [alexdean/persistent_hash#3]
Following the instructions in the readme running `rake persistent_hash:install:migrations` works, but then running `rake db:migrate` results in 

```
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for
```

**Comment by alexdean** [comment]
@jhirbour please try out the `rails-5` branch. if you can confirm that fixes the issue, i'll merge it and do a release.
